#!/usr/bin/env ucode
/**
 * Economy: domain → nft set via dnsmasq nftset=
 * Community services from itdoginfo/allow-domains Services/*.lst
 */

let fs = require("fs");

const CONFIG_NAME = getenv("FORKOP_CONFIG_NAME") || "forkop";
const NFT_TABLE = getenv("NFT_TABLE_NAME") || "ForkopTable";
const DNSMASQ_CONF_DIR = getenv("FORKOP_DNSMASQ_CONF_DIR") || "/tmp/dnsmasq.d";
const NFTSET_CONF = DNSMASQ_CONF_DIR + "/forkop-economy-nftset.conf";
const DOMAIN_LIST_DIR = getenv("FORKOP_DOMAIN_LIST_DIR") || "/tmp/forkop/domain-lists";
const GITHUB_RAW_URL = getenv("GITHUB_RAW_URL") || "https://raw.githubusercontent.com/itdoginfo/allow-domains/main";

function as_string(value) {
    return value == null ? "" : "" + value;
}

function ensure_dir(path) {
    return system("mkdir -p '" + replace(as_string(path), /'/g, "'\\''") + "'") == 0;
}

function set_name_for_section(section_name, family) {
    let safe = replace(as_string(section_name), /[^A-Za-z0-9_]/g, "_");
    if (length(safe) > 40)
        safe = substr(safe, 0, 40);
    return "eco_" + safe + (family == 6 ? "_v6" : "_v4");
}

function normalize_domain(value) {
    value = lc(trim(as_string(value)));
    value = replace(value, /^\.+/, "");
    value = replace(value, /\.$/, "");
    if (index(value, "regex:") == 0 || index(value, "keyword:") == 0)
        return "";
    if (index(value, "full:") == 0)
        value = substr(value, 5);
    if (value == "" || index(value, "/") >= 0 || index(value, " ") >= 0)
        return "";
    if (match(value, /^[0-9]+(\.[0-9]+){3}(\/[0-9]+)?$/))
        return "";
    return value;
}

function download_community_lst(service) {
    service = as_string(service);
    if (service == "")
        return null;
    ensure_dir(DOMAIN_LIST_DIR);
    let path = DOMAIN_LIST_DIR + "/" + service + ".lst";
    let url = GITHUB_RAW_URL + "/Services/" + service + ".lst";
    let st = fs.stat(path);
    let need = st == null;
    if (!need) {
        let data = fs.readfile(path);
        if (data == null || length(trim(as_string(data))) == 0)
            need = true;
    }
    if (need)
        system("wget -q -O '" + replace(path, /'/g, "'\\''") + "' '" + replace(url, /'/g, "'\\''") + "' 2>/dev/null");
    if (fs.stat(path) == null)
        return null;
    return path;
}

function add_domains_from_file(path, add_dom) {
    let data = fs.readfile(path);
    if (data == null)
        return;
    for (let line in split(as_string(data), "\n")) {
        line = trim(replace(line, /#.*$/, ""));
        if (line == "")
            continue;
        if (match(line, /^[0-9a-fA-F:.]+(\/[0-9]+)?$/))
            continue;
        add_dom(line);
    }
}

function section_names_list() {
    let names = [];
    let p = fs.popen("uci -q show " + CONFIG_NAME + " 2>/dev/null | grep '=section$' | cut -d. -f2 | cut -d= -f1", "r");
    let raw = p != null ? p.read("all") : "";
    if (p != null)
        p.close();
    for (let n in split(as_string(raw), "\n")) {
        n = trim(n);
        if (n != "" && n != "settings")
            push(names, n);
    }
    return names;
}

function uci_get(key) {
    let p = fs.popen("uci -q get " + key + " 2>/dev/null", "r");
    let v = p != null ? trim(as_string(p.read("all"))) : "";
    if (p != null)
        p.close();
    return v;
}

function generate_nftset_conf() {
    ensure_dir(DNSMASQ_CONF_DIR);
    ensure_dir(DOMAIN_LIST_DIR);

    let lines = [];
    push(lines, "# Generated by Forkop economy — domain → nft set");

    for (let name in section_names_list()) {
        let ev = uci_get(CONFIG_NAME + "." + name + ".enabled");
        if (ev == "0" || ev == "false")
            continue;
        let action = uci_get(CONFIG_NAME + "." + name + ".action");
        if (action == "dns")
            continue;

        let domains = [];
        let seen = {};
        function add_dom(v) {
            v = normalize_domain(v);
            if (v == "" || seen[v])
                return;
            seen[v] = true;
            push(domains, v);
        }

        for (let key in ["domain", "domain_suffix"]) {
            for (let v in split(uci_get(CONFIG_NAME + "." + name + "." + key), /[ \t\n]/))
                add_dom(v);
        }

        for (let svc in split(uci_get(CONFIG_NAME + "." + name + ".community_lists"), /[ \t\n]/)) {
            svc = trim(svc);
            if (svc == "")
                continue;
            let lst = download_community_lst(svc);
            if (lst != null)
                add_domains_from_file(lst, add_dom);
        }

        if (length(domains) == 0)
            continue;

        let set4 = set_name_for_section(name, 4);
        let set6 = set_name_for_section(name, 6);
        let chunk = [];
        let chunk_size = 40;
        for (let i = 0; i < length(domains); i++) {
            push(chunk, domains[i]);
            if (length(chunk) >= chunk_size || i == length(domains) - 1) {
                let path = "/" + join("/", chunk) + "/";
                push(lines, "nftset=" + path + "4#inet#" + NFT_TABLE + "#" + set4);
                push(lines, "nftset=" + path + "6#inet#" + NFT_TABLE + "#" + set6);
                chunk = [];
            }
        }
        push(lines, "# section " + name + " action=" + action + " domains=" + length(domains));
    }

    let body = join("\n", lines) + "\n";
    if (!fs.writefile(NFTSET_CONF, body))
        return { ok: false, path: NFTSET_CONF, error: "write failed" };

    system("/etc/init.d/dnsmasq reload >/dev/null 2>&1 || killall -HUP dnsmasq 2>/dev/null");
    return { ok: true, path: NFTSET_CONF, lines: length(lines) };
}

function conf_path() {
    return NFTSET_CONF;
}

return {
    set_name_for_section,
    generate_nftset_conf,
    conf_path,
    normalize_domain,
    download_community_lst
};
